### ISSUE TITLE
Mocking SoapFault throws a fatal error

### ISSUE THREAD

**Issue by josephharrington** [phake/phake#208]
This is related to the [SoapFault class](http://php.net/manual/en/class.soapfault.php), which is defined in C. This actually might be more PHP's fault, but I just wanted to record this here since Phake might want to work around it. For reference, I'm on Phake 2.2 and PHP 5.4.41.

The code

``` php
Phake::mock('SoapFault');
```

will throw a fatal:

```
Fatal error: Cannot redeclare SoapFault_PHAKE5665ef87229261::__construct() in ./vendor/phake/phake/src/Phake/ClassGenerator/EvalLoader.php(58) : eval()'d code on line 60

Call Stack:
    0.0003     226960   1. {main}() ./.ignore/x_soapfault.php:0
    0.0097    1148920   2. Phake::mock() ./.ignore/x_soapfault.php:95
    0.0107    1307696   3. Phake_Facade->mock() ./vendor/phake/phake/src/Phake.php:98
    0.0108    1308440   4. Phake_ClassGenerator_MockClass->generate() ./vendor/phake/phake/src/Phake/Facade.php:96
    0.0110    1314024   5. Phake_ClassGenerator_EvalLoader->loadClassByString() ./vendor/phake/phake/src/Phake/ClassGenerator/MockClass.php:232
```

It seems to be related to [this line](https://github.com/mlively/Phake/blob/9919929d/src/Phake/ClassGenerator/MockClass.php#L317) in MockClass.php:

``` php
if (!$method->isConstructor() && !$method->isDestructor() && !$method->isFinal()
```

specifically `$method->isConstructor()` looks like it's returning false for `SoapFault::__construct()`.

I can actually work around this by declaring a dumb wrapper class with a __construct() method that just calls through to the parent construct, and then do a mock on the wrapper class, but obviously that's not ideal.

**Comment by adoy** [comment]
Issue was due to the Fact that `SoapFault::__construct` was not actually the constructor since it was defined at `SoapFault::SoapFault`. This was deprecated in PHP7.0. Closing this issue.
