### ISSUE TITLE
Cannot pass values by reference when using Phake::makeVisible()

### ISSUE THREAD

**Issue by priyajeet** [phake/phake#224]
``` php
class Foo
{
    protected function bar(array &$errors)
    {
        // do stuff
    }
}
```

``` php
$errors = [];
$foo = Phake::partialMock('Foo');
Phake::makeVisible($foo)->bar($error);
// asserts
```

The above code fails complaining about argument 1 is not a reference and instead is a value.
Making `bar()` public and not using `Phake::makeVisible()` works as intended.

**Comment by adoy** [comment]
As stated by PHP Documentation :
> None of the arguments of these magic methods can be passed by reference
