### ISSUE TITLE
Is this project abandoned? 

### ISSUE THREAD

**Issue by willemstuursma** [phake/phake#264]
Looking at the lists of open pull requests, issues and the last releases it doesn't seem like you are able to invest a lot of time into this project @mlively.

Clearly, lots of people are depending on this project.

Would you be willing to transition ownership to a new organization so that a fresh team of developers can take over the project?

**Comment by willemstuursma** [comment]
Cool! Would you like to add maintainers here or move to a new organization (e.g. `phake/phake`) first?

I'll recruit a bit in my organization, we have lots of Phake lovers at Mollie.

**Comment by 20uf** [comment]
It's nice idea create and move in a new organization.

**Comment by fattouchsquall** [comment]
i approve this idea, very interested by this project.

Bien cordialement.

*Amine FATTOUCH*
*Symfony Architect*

*Email.  amine.fattouch@gmail.com <amine.fattouch@gmail.com>*
*Github.  **https://github.com/fattouchsquall
<https://github.com/fattouchsquall>*

2018-05-29 10:47 GMT+02:00 Michael COULLERET <notifications@github.com>:
