### ISSUE TITLE
Phake v4 is not compatible with PHPUnit 10.

### ISSUE THREAD

**Issue by niconoe-** [phake/phake#311]
PHPUnit 10.0 has been released on Feb, the 3rd, and it uses internally a new version of [sebastian/comparator](https://github.com/sebastianbergmann/comparator), the version 5 of it.

The current Phake v4 requires sebastian/comparator until v4 included, so this gives the impossibility to use PHPUnit 10 with Phake.

But there is more: PHPUnit 10 is now only supported for PHP 8.1 and PHP 8.2, while Phake was supported for `^7.1|^8.0`. That means if Phake wants to support PHPUnit 10, a new Phake version v5 must be created with `"php":"^8.1"` as a requirement, and stop the support of PHP version older than 8.1.

Is this something Phake can handle?

Thanks a lot

**Comment by adoy** [comment]
I haven't looked at the changes in Comparator 5 yet. I'll try to look at it later this week. 

As far as compatibility, I'm not sure if an API change is needed in Phake4 so for now, there are no plans to have a Phake5.

**Comment by niconoe-** [comment]
Thanks for the information.

> As far as compatibility, I'm not sure if an API change is needed in Phake4 so for now, there are no plans to have a Phake5.

Ok, no problem for me. I thought that it was on your policies to update the major version of Phake when the compatibilty with previous PHP version can't be assured, but I probably made this assumption too fast ;).

Anyway, thanks for taking a look. On my side, as I'm a Phake user a lot and I need my projects to be ready for PHPUnit 10, I'll also try to take a look at the changes the comparator v5 brings, and how it impacts Phake.

**Comment by adoy** [comment]
I quickly created a `phpunit10` branch that you should be able to use with `"phake/phake": "phpunit10-dev"`. Let me know if you find anything. I'll have to do some more tests and research on what changed in both PHPUnit10 and Comparator v5 but at least Phake tests are working with this version.

**Comment by niconoe-** [comment]
Thanks a lot for providing the branch. After some tests I made, everything is OK on Phake point of view. My unit tests need some updates, but that's not related to Phake, and the library still works like a charm with the changes you brought on `phpunit10` branch.

Thanks a lot again, and I can't wait for it to be released :slightly_smiling_face:

**Comment by adoy** [comment]
@niconoe- Thank you for the quick feedback. I will take a bit more time this week to make sure there are no other impacts and to test the new version on other projects. However, from what I can see in the PhpUnit and Comparator CHANGELOGs, everything should be alright.

If I do not find any issue I'll do a release before the end of the week.

**Comment by niconoe-** [comment]
Wonderful! Thank you very much about it.

Having a release at the end of the week is perfect :slightly_smiling_face:
