### ISSUE TITLE
4.4 branch has Composer validation errors

### ISSUE THREAD

**Issue by bfeaver** [phake/phake#316]
Packagist is complaing about the 4.4 branch's composer.json being invalid. This is spamming email when it attempts to update in Packagist. You can check out 4.4 and run `composer validate` to see the error.

```
Skipped branch experimental/types, Invalid package information:
extra.branch-alias.dev-4.4 : the target branch (4.4) must end in -dev

Skipped branch 4.4, Invalid package information:
extra.branch-alias.dev-4.4 : the target branch (4.4) must end in -dev
```

**Comment by adoy** [comment]
Hi Brian, sorry about that. It should be fix. Would it be possible to add me on packagist ? I asked Mike but got no answer since. It will help me see those kind of cases.

Thanks in advance.

**Comment by bfeaver** [comment]
I added you as a maintainer in Packagist. 👍

**Comment by adoy** [comment]
Thanks a lot. I close this issue. If you still see something wrong, feel free ton reopen it.
