### ISSUE TITLE
Compatibility with PHPUnit 11

### ISSUE THREAD

**Issue by niconoe-** [phake/phake#320]
Hi!

PHPUnit 11 has ben released a few days ago, and there are IMO some missing adaptations to do on Phake.

- [ ] On https://github.com/phake/phake/blob/231f306d9afe08df84e8dd9299f9ce20dc710f23/src/Phake.php#L73-L77 the `public const CLIENT_PHPUNIT11 = 'PHPUNIT11';` new constant should be added.
- [ ] On https://github.com/phake/phake/blob/231f306d9afe08df84e8dd9299f9ce20dc710f23/src/Phake.php#L482-L507 the handling of PHPUnit 11 (with a client defined exactly as the one from PHP Unit 10 as there are no changes) should be done
- [ ] Copy the https://github.com/phake/phake/blob/231f306d9afe08df84e8dd9299f9ce20dc710f23/src/Phake/Client/PHPUnit10.php class into a `PHPUnit11` one.

And I think that's ok :wink: 

Thanks a lot!

**Comment by adoy** [comment]
I'll do my best to work on this this week-end end do a release. Thanks

**Comment by niconoe-** [comment]
Hey @adoy I hope you're well :slightly_smiling_face: 

I know you talked about working on this but it looks like you are currently busy on something else. Do you want me to provide a PR for this? Do you also want me provide additionnal changes regarding the PHPUnit 11 compatibility?

Thanks a lot :wink:

**Comment by niconoe-** [comment]
:facepalm: I just did it from `master`… I think that's not the "last stable branch" you talked about…

I'll replicate the changes from branch 4.4. Sorry for that…

**Comment by niconoe-** [comment]
@adoy I think you can close this now Phake 4.5 is compatible.

Thanks for taking care!
